### ISSUE TITLE
derep_vsearch zOTUs appearing in fasta but not zotu_table

### ISSUE THREAD

**Issue by cajwalsh** [mhoban/rainbow_bridge#73] opened 2024-07-15 14:44 UTC
I'm not really sure that this is an eDNAFlow problem, but I noticed today that in one of my datasets (starting with --demuxed-fasta) I am getting several zOTUs that don't show up in the main zOTU table itself. This is the first time I have encountered this. I did not run lulu yet the main zotu_table just skips their zOTU number even though they appear to have a valid number of sequences and have been included in the zOTUs.fasta file. In this case, the zotu fasta file contains 4232 sequences, 11 more zotus than are included in the zOTU table. These zOTU names range from the low 800s to mid 3000s. Roughly half of them were not assigned a domain (insect) and the other half were mycthophids. Below is the last two parts of the derep_vsearch .command.err. Is it possible that in the last step none of the reads were mapped back to the 11 missing zOTUs?

Reading file eDNAFlow_centroids.fasta 100%
2514512 nt in 13812 seqs, min 62, max 283, avg 182
Masking 100%
Sorting by abundance 100%
Counting k-mers 100%
Detecting chimeras 100%
Found 9580 (69.4%) chimeras, 4232 (30.6%) non-chimeras,
and 0 (0.0%) borderline sequences in 13812 unique sequences.
Taking abundance information into account, this corresponds to
524985 (2.8%) chimeras, 18556368 (97.2%) non-chimeras,
and 0 (0.0%) borderline sequences in 19081353 total sequences.
vsearch v2.10.4_linux_x86_64, 94.3GB RAM, 32 cores
https://github.com/torognes/vsearch

Reading file eDNAFlow_zotus.fasta 100%
848421 nt in 4232 seqs, min 62, max 283, avg 200
Masking 100%
Counting k-mers 100%
Creating k-mer index 100%
Searching 100%
Matching query sequences: 32227200 of 33331190 (96.69%)
Writing OTU table (classic) 100%

I thought maybe they might've gotten merged into bigger ones if they were smaller too but the 11 "missing" (MiFishU) zOTUs were all median size or larger relative to all zOTUs in the zotu fasta.

Overall:
Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   62.0   169.0   171.0   200.5   256.0   283.0

Missing:
Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    172     180     256     227     256     257

I don't really need a fix for this as I guess it is fine to just use the otu table, I just haven't experienced something like this and wanted to put it here for now in case we think of a reason for it or just in case it is somehow linked (since it's losing a similar number of zOTUs) to what was mentioned in #72

**Comment by mhoban** [comment] 2024-10-16 07:04
Closing as a duplicate of #85

**Closed by mhoban** 2024-10-16 07:04 UTC
Labels: duplicate
